### PR TITLE
Upgrade vs2017

### PR DESCRIPTION
**Pull request by allywarner**
Does not build testing yet.

### CODE REVIEW

**Comment by allywarner** [comment]
Upgrade of testing complete!

**Comment by allywarner** [comment]
OSX build fixed.

**Comment by allywarner** [comment]
There functions or wrappers written in the ITK namespace using ITK includes. Does it have to be changed for this pull request or could we make a separate issue to rename?

**Comment by dcwhite** [comment]
separate issue (not even worth a full one really)

**Comment by allywarner** [comment]
Renamed and successful Windows and OSX builds.

**Comment by dcwhite** [comment]
Just waiting on my Windows build to finish!

**Pull request merged**
