### PR TITLE
Experiment: Adding a wait to check for render resources to be available.

### PR DESCRIPTION
**Pull request by mildewey**

### CODE REVIEW

**Comment by dcwhite** [comment]
@mildewey Non-master branches are not protected, so you can just merge this yourself. Did you want someone else to look at or test it out?

**Comment by mildewey** [comment]
I'm not sure I want to merge it yet. I'll have Ally take a look at it when
she gets back.

**Comment by mildewey** [comment]
I'm planning on leaving it here until Ally can take a look and ensure it fixes something.

**Comment by dcwhite** [comment]
That's what I suspected. I wish there was a way to enable/enforce NOT merging a PR on github, other than adding a very obvious note in the description. I will leave it alone then.

**Pull request closed without merging**
